[package]
name = "sv-language-index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
generational-arena = "0.2.8"
sv-parser = ">=0.12"
